monitoring.webui/urls.py
# -*- coding: utf-8 -*-
# Copyright (C) Canux CHENG <canuxcheng@gmail.com>
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
# DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
# OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

from django.conf.urls import *
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView

from monitoring.webui.views import UserEdit, MaintenanceView

urlpatterns = patterns('monitoring.webui.views',
    # Login / Logout
    url(r'^accounts/login/$',
        view='http_login',
        name='login'),
    url(r'^accounts/profile/$',
        view=login_required(UserEdit.as_view()),
        name='user_profile'),

    (r'^maintenance/$', MaintenanceView.as_view()),

    (r'^error/404/$', TemplateView.as_view(template_name='404.html')),
    (r'^error/500/$', TemplateView.as_view(template_name='500.html')),
)

optools/urls.py
# -*- coding: utf-8 -*-
# Copyright (C) Canux CHENG <canuxcheng@gmail.com>
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
# DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
# OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

from django.conf.urls import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin

admin.autodiscover()

handler500 = 'monitoring.webui.views.server_error'

urlpatterns = patterns('',
    # Admin
    (r'^admin/', include(admin.site.urls)),

    # Applications
    # ============
    #
    # Portal
    (r'', include('apps.portal.urls')),
    (r'', include('monitoring.webui.urls')),
    (r'', include('apps.kpi.urls')),
    (r'^nagios/', include('apps.nagios.urls')),
    (r'^kb/', include('apps.kb.urls')),
)

apps/kb/models.py
"""
:mod:`apps.kb.models` -- Models for app kb.
"""

# Std imports
import os
import logging
import re
from datetime import datetime
from pprint import pformat

# Django imports
from django.utils.encoding import smart_str
from django.db import models
from django.core.exceptions import ValidationError
from django.utils.timezone import utc
from django.conf import settings


logger = logging.getLogger(__name__)

#===============================================================================
#   ____ _
#  / ___| | __ _ ___ ___  ___  ___
# | |   | |/ _` / __/ __|/ _ \/ __|
# | |___| | (_| \__ \__ \  __/\__ \
#  \____|_|\__,_|___/___/\___||___/
#
#===============================================================================

class Procedure(models.Model):
    """
    Procedure Model.
    Store informations about KB from Dokuwiki to a database.
    """
    namespace_regexp = r'^([a-zA-Z0-9_\-\.\+]+:*)+$'

    class MetaError(Exception):
        """Raised if error is encountered during meta file parsing."""
        pass

    # Possible rating choices
    RATING_CHOICES = (
        (-2, 'Bad'),
        (-1, 'Average'),
        ( 0, 'Good'),
        ( 1, 'Excellent'),
    )

    # Table columns
    namespace = models.CharField(max_length=255, unique=True, help_text='Namespace for this procedure.', editable=False)
    is_written = models.BooleanField(help_text='Is the procedure has been written ?', default=False, editable=False)
    validated = models.BooleanField(help_text='Is the procedure is validated ?', default=False, editable=False)
    author = models.CharField(max_length=128, help_text='Last modification author.', blank=True, null=True, editable=False)
    parents = models.ManyToManyField('Procedure', help_text='These are the parent procedures.', null=True, editable=False)
    rating = models.IntegerField(choices=RATING_CHOICES, help_text='Rating for this procedure.', default=-1)
    comment = models.TextField(help_text='Comment on the grade you given.', blank=True, null=True)
    last_modified = models.DateTimeField(help_text='Time of the last modification.', blank=True, null=True, editable=False)

    # KB constructor: register a new KB in the database with all details (without performing DB stuff)
    @classmethod
    def register(cls, namespace):
        procedure = cls(namespace=namespace)

        procedure._strip_namespace()
        procedure.update_meta()

        return procedure

    # Saving
    def save(self, *args, **kwargs):
        """Customize saving model method."""
        try:
            # Call validation manually
            self.full_clean()
        except ValidationError as e:
            logger.critical('Errors found about Procedure model validation ! Please fix them.')
            for error in e.message_dict['__all__']:
                logger.critical('%s', error)
            raise # Forward exception

        self.update_meta()

        # Check validation of the procedure
        try:
            before = Procedure.objects.get(pk=self.id)

            # Rating has changed...
            if self.rating != before.rating:
                logger.debug('Kb \"%s\" rating has changed. Validate.', self)
                self.validated = True

            # Last modified has changed...
            if self.last_modified != before.last_modified:
                logger.debug('Kb \"%s\" has been modified. Un-validate.', self)
                self.validated = False
        except Procedure.DoesNotExist:
            pass

        # Save in DB
        super(Procedure, self).save(*args, **kwargs)

    # Special KB methods
    def update_meta(self):
        """Update META information about the procedure."""
        # Check if file exist for the procedure
        if os.path.isfile(self.get_filename()):
            self.is_written = True
        else:
            self.is_written = False

        # Update META informations
        self._populate_meta()

    def get_name(self):
        """Get the name for this procedure."""
        return self.namespace.split(':')[-1]

    def get_filename(self):
        """Get the filename for this procedure."""
        return os.path.join(settings.DOKUWIKI_PAGES_DIR, "{}.txt".format(self.namespace.replace(':', '/')))

    def get_changes_filename(self):
        """Get the filename containing changes for this procedure."""
        return os.path.join(settings.DOKUWIKI_META_DIR, "{}.changes".format(self.namespace.replace(':', '/')))

    def get_read_url(self):
        """Get the URL to read the procedure online."""
        return '{}/{}'.format(settings.DOKUWIKI_BASE_URL, self.namespace)

    def get_edit_url(self):
        """Get the URL to edit the procedure online."""
        return '{}/{}?do=edit'.format(settings.DOKUWIKI_BASE_URL, self.namespace)

    def _populate_meta(self):
        """Populate META information about the Kb."""
        try:
            with open(self.get_changes_filename(), 'r') as meta_file:
                last_change = meta_file.readlines()[-1].split('\t')
                logger.debug("Parsing line:\n%s", pformat(last_change))
                self.last_modified = datetime.fromtimestamp(long(last_change[0]), tz=utc)
                self.author = last_change[4]
        except IOError:
            # Do nothing. No meta information available, procedure may not exist
            logger.debug('No META information for \"%s\".', self)
            pass
        except ValueError:
            # Can occur if timestamp cannot be converted to datetime or if it is not found
            raise Procedure.MetaError('Error during meta file \"%s\" parsing !' % self.get_changes_filename())

    def _strip_namespace(self):
        """
        Clean and validate namespace.
        """
        logger.debug('Cleaning namespace \'%s\'...', self.namespace)
        self.namespace = self.namespace.lower().strip(':')

        if not re.match(Procedure.namespace_regexp, self.namespace):
            raise ValidationError('KB namespace should be of the form %s !' % Procedure.namespace_regexp)

        logger.debug('Namespace cleaned to \'%s\'.', self.namespace)

    def get_parents(self):
        """
        Build the list of parent namespaces for the procedure.

        :return: parent list for procedure ``['app:toto', 'app:toto:tata', '...']``.
        """
        parents_to_build = []
        parents = filter(str, self.namespace.split(':')[:-1])

        for index, parent in enumerate(parents):
            index += 1
            parents_to_build.append(":".join(parents[:index]))

        return parents_to_build

    def _linkify_parents(self):
        """Make parents relations."""
        for parent_name in self.get_parents():
            try:
                parent_model = Procedure.objects.get(namespace=parent_name)
            except Procedure.DoesNotExist:
                parent_model = Procedure.register(namespace=parent_name)

            self.parents.add(parent_model)

    # Comparaison operators
    def __eq__(self, other):
        if isinstance(other, (str, unicode)):
            return other == self.namespace
        elif isinstance(other, Procedure):
            return self.namespace == other.namespace

        super(Procedure, self).__eq__(other)

    # Misc
    def __str__(self):
        return smart_str(self.namespace)

    def __unicode__(self):
        return self.namespace

    def __hash__(self):
        return hash(self.namespace)

monitoring.webui/views.py
# -*- coding: utf-8 -*-
# Copyright (C) Canux CHENG <canuxcheng@gmail.com>
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
# DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
# OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

# Std imports
import logging

# Django imports
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.views.decorators.cache import never_cache
from django.views.generic import UpdateView, TemplateView
from django.conf import settings
from django.contrib.auth import authenticate, login
from django.http import HttpResponse
from django.utils.decorators import method_decorator

# Project imports
from monitoring.webui.forms import UserEditForm

# 3rd party
import httpagentparser


logger = logging.getLogger(__name__)


def http_login(request):
    """
    Called after successfull basic HTTP authentication and check if user filled
    his profile.
    """
    logger.debug('Request full path: %s', request.get_full_path())
    redirection = ""

    # Should we redirect after login ?
    if "next" in request.GET:
        qr = request.GET.copy()
        next_url = qr.pop('next')[0]
        remains = qr.urlencode()
        redirection = '{0}?{1}'.format(next_url, remains)
        logger.debug('Should redirect to: %s', redirection)

    # Find user
    if settings.DEBUG:
        user = User.objects.get(username='test@corp')
        userauth = authenticate(username=user.username, password='test')
        login(request, userauth)
    else:
        user = User.objects.get(username=request.META['REMOTE_USER'])

    operating_system, browser = httpagentparser.simple_detect(
        request.META.get('HTTP_USER_AGENT'))
    logger.info('%s logged in using browser %s on %s.',
                user.username, browser, operating_system)

    # Validation
    if not user.is_active \
       or user.username.startswith('0') \
       or not user.username.endswith('@corp'):
        # Be sure that the login will not be used anymore
        user.is_active = False
        user.save()
        logger.info('User name %s is mal-formed !', user.username)
        return HttpResponse('Invalid account. Please use your '
                            '<strong>normal</strong> user account and append '
                            '<em>@corp</em>.')

    # Auto fill profile (if possible)
    user.first_name = request.META.get('AUTHENTICATE_GIVENNAME', '')
    user.last_name = request.META.get('AUTHENTICATE_SN', '')
    user.email = request.META.get('AUTHENTICATE_MAIL', '')
    user.save()

    if (user.first_name or user.last_name) and user.email:
        if redirection:
            response = redirect(redirection)
        else:
            response = redirect('index')
    else:
        # Profile is not completed
        logger.info('User %s has not filled his profile.', user.username)
        if redirection:
            response = redirect('%s?redirect=%s' % (reverse('user_profile'),
                                                    redirection))
        else:
            response = redirect('user_profile')

    return response


class UserEdit(UpdateView):
    """
    Class based view to show the User profile editing form.
    """
    form_class = UserEditForm
    model = User

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(UserEdit, self).get_context_data(**kwargs)
        return context

    def get_object(self, queryset=None):
        obj = User.objects.get(username=self.request.user)
        return obj

    def get_success_url(self):
        try:
            return self.request.GET['redirect']
        except KeyError:
            return reverse("index")


def server_error(request):
    """
    Handle 500 error codes.
    """
    return render(request, "500.html", {'title': "Severe error !"})


class MaintenanceView(TemplateView):
    """
    Show a nice maintenance page for various operations.

    :param origin:
        Indicates to which target URL the maintenance page must
        redirect the user after 60 seconds.
    :type origin: GET
    :param category:
        Maintenance category, depends on the type of operation
        being performed. Try to load the template
        ``maintenance/<category>.html``.
    :type category: GET
    """
    template = "maintenance/{name}.html"

    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        return super(MaintenanceView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(MaintenanceView, self).get_context_data(**kwargs)
        context['category'] = self.request.GET.get("category", 'default')
        context['origin'] = self.request.GET.get("origin", None)

        self.category = context['category']

        return context

    def get_template_names(self):
        return MaintenanceView.template.format(name=self.category)

monitoring.webui/templates/common/_footer.html
{% comment %}
This is the default Footer content.
Overrides block "footer" if you want to manage your own footer.
Overrides block "footer_content" if you want to only change the middle part of the footer.
{% endcomment %}

<div class="col-md-5">
    <p>Propulsed by <a
            href="https://www.djangoproject.com/"
            rel="tooltip"
            title="Django is a high-level Python Web framework that encourages rapid development and clean, pragmatic design."
            target="_blank">Django</a> & <a
            href="http://www.python.org/" rel="tooltip"
            title="Python is a programming language that lets you work more quickly and integrate your systems more effectively."
            target="_blank">Python</a>.</p>

    <p>Presented with <a
            href="http://twitter.github.com/bootstrap/"
            rel="tooltip"
            title="Sleek, intuitive, and powerful mobile first front-end framework for faster and easier web development."
            target="_blank">Twitter
        Bootstrap</a> HTML5/CSS3 framework.</p>
    {% block extra_footer %}{% endblock extra_footer %}
</div>

monitoring.webui/templates/common/_navbar.html
{% comment %}
This is the default Navbar.
Overrides block "navbar" if you want another navbar content.
{% endcomment %}

{% load gravatar %}

<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="navbar-header">
        <!-- Toggle menu for low width -->
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <!-- Brand name -->
        <a class="navbar-brand" href="{% url "index" %}">Central Systems</a>
    </div>

    <!-- Main menu -->
    <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
            <!-- Home -->
            <li class="{{ section.home }}"><a href="{% url "index" %}"><span class="glyphicon glyphicon-home"></span> Portal</a></li>

            <!-- Reporting -->
            <li class="{{ section.kpi }}"><a href="{% url "apps.kpi.indicateurs.indicateurs" %}"><span class="glyphicon glyphicon-stats"></span> Reporting</a></li>

            <!-- KB -->
            <li class="{{ section.kb }} dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">KB <b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li><a href="/kb/?do=index" target="_blank">Index</a></li>
                    {% if perms.kb.change_procedure %}
                        <li><a href="{% url "admin:kb_procedure_changelist" %}">Rate</a></li>
                    {% endif %}
                </ul>
            </li>

            <!-- Web APIs -->
            <li><a href="/doc/api/"><span class="glyphicon glyphicon-book"></span> APIs</a></li>

            <!-- Systems -->
            <li class="{{ section.systems }} dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Systems <b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li><a href="{% url "systems_list" %}">Nagios Satellites</a></li>
                    <li><a href="http://canuxcheng.com/puppet/">Puppet Dashboard</a></li>
                </ul>
            </li>

            <!-- Administration -->
            {% if user.is_authenticated and user.is_staff %}
                <li class="nav-divider"></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-wrench"></span> Administration <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li class="dropdown-header">Auth</li>
                        <li><a target="_blank" href="{% url "admin:auth_user_changelist" %}">Users</a></li>
                        <li><a target="_blank" href="{% url "admin:auth_group_changelist" %}">Groups</a></li>
                    </ul>
                </li>
            {% endif %}
        </ul>

        <!-- Profile -->
        <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">{% if user.email %}{% gravatar_img_for_email user.email 14 %}{% else %}<span class="glyphicon glyphicon-user"></span>{% endif %} Welcome, {{ user.first_name|default:"NoName" }} <b class="caret"></b></a>
                    <ul id="dropdown_profile" class="dropdown-menu">
                        <li><div>{% gravatar_img_for_email user.email 64 %} <strong>{% if user.first_name and user.last_name %}{{ user.first_name }} {{ user.last_name }}{% else %}Edit your profile !{% endif %}</strong></div></li>
                        <li class="divider"></li>
                        <li><a href="{% url "user_profile" %}">Edit profile</a></li>
                    </ul>
                </li>
            {% else %}
                <li><a href="#modal-prelogin-message" data-toggle="modal">Login</a></li>
            {% endif %}
            {% if PROJECT_DEBUG_MODE %}
                <li><a rel="tooltip" title="You are in DEBUG mode !" data-placement="bottom">Database: <strong>{% if PROJECT_DB_HOST %}!! PROD !!{% else %}TEST{% endif %}</strong></a></li>
            {% endif %}
        </ul>
    </div>
</nav>

monitoring.webui/templates/common/base.html
{% extends "common/html_headers.html" %}

{% block content %}
    <!-- Navbar -->
    {% block navbar %}
        {% include "common/_navbar.html" %}
    {% endblock navbar %}

    <!--[if lt IE 9]>
    <div id="browser_outdated" class="alert alert-danger">
      <h3><strong><span class="glyphicon glyphicon-bell"></span> Your browser is not up-to-date !</strong></h2>
      <p><strong>Please note that we no longer supports Internet Explorer versions below 8.</strong><p>
      <p>We recommend upgrading to the latest <a href="https://ie.microsoft.com/">Internet Explorer</a> or <a href="https://mozilla.org/firefox/">Firefox</a>.</p>
      <p>If you are using IE 9 or later, make sure you turn off <a href="http://windows.microsoft.com/en-US/windows7/webpages-look-incorrect-in-Internet-Explorer">"Compatibility View"</a>.</p>

      <p class="alert alert-info">You may experience poor browsing if you continue.</p>
      <p class="alert alert-success"><strong>Please ask your system administrator to upgrade your browser.</strong></p>
    </div>
    <![endif]-->

    <!-- Page content -->
    {% block page_content %}{% endblock page_content %}
    <!-- /Page content -->
{% endblock content %}

{% block footer %}
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <p>
                        <a href="mailto:canuxcheng@gmail.com">
                            Central Systems / Monitoring &amp; Reporting</a>,
                        2006-{{ current_year|default:"Present" }}
                    </p>

                    <p>
                        <small>optools <a target="_blank"
                                          href="http://canuxcheng.com/git/?p=admin/optools.git;a=shortlog;h=refs/heads/master">v{{ PROJECT_VERSION }}</a>
                        </small>
                        <br/>
                        <small>webui <a target="_blank"
                                          href="http://canuxcheng.com/git/?p=lib/monitoring.webui.git;a=shortlog;h=refs/heads/master">v{{ WEBUI_VERSION }}</a>
                        </small>
                    </p>
                </div>

                {% block footer_content %}
                    {% include "common/_footer.html" %}
                {% endblock footer_content %}

                <div class="col-md-3">
                    <p>
                        <a class="pull-right logo-canux"
                           href="http://intranet.canux/"
                           target="_blank"></a>
                    </p>
                </div>
            </div>
        </div>
    </footer>
{% endblock footer %}

monitoring.webui/templates/common/html_headers.html
<!DOCTYPE html>
<!--
# Copyright (C) Canux CHENG <canuxcheng@gmail.com>
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
# DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
# OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
-->
{% block root %}
  <html lang="en">
  {% block header %}
    <head>
      <title>Central Systems |
        {% block page_title %}{% endblock page_title %}</title>

      <!-- Meta -->
      {% block meta %}
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="author"
              content="Central Systems / Canux CHENG">
        <meta name="copyright"
              content="(c) 2011-2013 Central Systems / Canux CHENG">
        <meta name="keywords"
              content="monitoring,nagios,operations,canux">
        <meta name="description"
              content="Provided by Central Systems / Canux CHENG">
        <meta name="viewport" content="width=device-width">

        <!-- Extra Meta (if any) -->
        {% block extra_meta %}{% endblock extra_meta %}
      {% endblock meta %}

      <!-- CSS -->
      {% block css %}
        <link rel="stylesheet"
              href="{{ STATIC_URL }}bootstrap/css/bootstrap.min.css">
        <link rel="stylesheet" href="{{ STATIC_URL }}common.css">

        <!-- Extra CSS (if any) -->
        {% block extra_css %}{% endblock extra_css %}
      {% endblock css %}

      <!--[if lt IE 9]>
      <script src="{{ STATIC_URL }}js/html5shiv.js"></script>
      <script src="{{ STATIC_URL }}js/respond.min.js"></script>
      <![endif]-->
    </head>
  {% endblock header %}

  {% block body %}
    <body>
    <!-- Body content -->
    {% block content %}{% endblock content %}

    <!-- Footer content -->
    {% block footer %}{% endblock footer %}

    <!-- Modal definition -->
    {% block modal %}
      {% include "auth/modal-prelogin-global_catalog.html" %}

      <!-- Extra Modal -->
      {% block extra_modal %}{% endblock %}
    {% endblock %}

    <!-- Scripts (at then end to load faster)   -->
    {% block script %}
      <!-- Jquery -->
      <script src="{{ STATIC_URL }}js/jquery-1.10.2.min.js"></script>

      <!-- Twitter Bootstrap -->
      <script src="{{ STATIC_URL }}bootstrap/js/bootstrap.min.js"></script>

      <!-- Extra Script (if any) -->
      {% block extra_script %}{% endblock extra_script %}

      <!-- Optools main -->
      <script src="{{ STATIC_URL }}js/optools.js"></script>
    {% endblock script %}
    </body>
  {% endblock body %}
  </html>
{% endblock root %}