apps/nagios/urls.py
# -*- coding: utf-8 -*-
# Copyright (C) Canux CHENG <canuxcheng@gmail.com>
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
# DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
# OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

from django.conf.urls import *

from apps.nagios.views import SatelliteListView

urlpatterns = patterns(
    'apps.nagios.views',
    url(r'^satellites/$',
        SatelliteListView.as_view(),
        name='systems_list'),
    url(r'^satellites/export/$',
        view='get_satellite_list'),
    url(r'^satellites/export/(?P<format>\w+)$',
        view='get_satellite_list',
        name='satellites_export'),
    url(r'^acknowledge/(?P<token>.*)$',
        view='acknowledge_token'),
    (r'^passive/$', 'send_passive'),
)

optools/urls.py
# -*- coding: utf-8 -*-
# Copyright (C) Canux CHENG <canuxcheng@gmail.com>
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
# DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
# OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

from django.conf.urls import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin

admin.autodiscover()

handler500 = 'monitoring.webui.views.server_error'

urlpatterns = patterns('',
    # Admin
    (r'^admin/', include(admin.site.urls)),

    # Applications
    # ============
    #
    # Portal
    (r'', include('apps.portal.urls')),
    (r'', include('monitoring.webui.urls')),
    (r'', include('apps.kpi.urls')),
    (r'^nagios/', include('apps.nagios.urls')),
    (r'^kb/', include('apps.kb.urls')),
)

apps/nagios/models.py
# -*- coding: utf-8 -*-
# Copyright (C) Canux CHENG <canuxcheng@gmail.com>
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
# DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
# OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

# Std imports
import logging

# Django imports
from django.db import models
from django.core.exceptions import ValidationError

# Apps imports
import apps.nagios.livestatus as live


# Logger for this app
logger = logging.getLogger(__name__)


# Validators
def validate_network_high_port(value):
    if not 1024 < value < 65536:
        raise ValidationError(u'Port number should be between 1024 - 65535')


def validate_network_port(value):
    if not 0 < value < 65536:
        raise ValidationError(u'Port number should be between 1 - 65535')


# Models
class Satellite(models.Model):
    """Model representing list of active Nagios satellites"""
    name = models.CharField(max_length=255, verbose_name='Satellite name',
                            help_text='Example for Hagenbach: HGB')
    active = models.BooleanField(
        default=False,
        verbose_name='Satellite is active',
        help_text='Is this satellite active for production ?')
    is_gearman = models.BooleanField(
        default=False,
        verbose_name='This is a Nagios/Gearman Satellite',
        help_text='Is this a Nagios/Gearman Satellite ?')

    # Network settings
    alias = models.CharField(
        max_length=255,
        verbose_name='Satellite alias',
        help_text='Please use following format: nagios.sss.cc.corp')
    fqdn = models.CharField(
        max_length=255,
        verbose_name='Satellite long name',
        help_text='Fully qualified domain name for the satellite')

    # Livestatus
    ip_address = models.IPAddressField()
    live_port = models.PositiveIntegerField(
        default=6557,
        validators=[validate_network_high_port],
        verbose_name='Livestatus port',
        help_text='Port must be between 1024 - 65536'
    )
    nagios_url = models.CharField(
        max_length=10,
        default='/nagios',
        verbose_name='Base URL',
        help_text='Use at your own risk ! Let it be default if you don\'t '
                  'know what you are doing')

    class Meta:
        ordering = ['name']

    # Exceptions classes for Livestatus connectivity
    class SatelliteConnectError(Exception):
        """
        Exception raised when a satellite is dead.
        """
        def __init__(self, *args, **kwargs):
            super(Satellite.SatelliteConnectError, self).__init__(*args,
                                                                  **kwargs)
            self.dead_satellites = args[0]

        def __str__(self):
            message = "Unable to connect / query satellites: "
            sat_errors = []
            for sat, value in self.dead_satellites.iteritems():
                sat_errors.append('{} ({})'.format(sat, value['exception']))
            message += ', '.join(sat_errors)

            return message

    # Customize livestatus connection class
    class SatelliteConnection(live.MultiSiteConnection):
        """
        Query / Connect to Livestatus peers.
        """
        def query(self, query, add_headers=""):
            q = live.MultiSiteConnection.query(self, query, add_headers)
            if self.dead_sites():
                exc = Satellite.SatelliteConnectError(self.dead_sites())
                logger.exception(exc)
                logger.info("Executed query:\n%s", query)
                raise exc

            return q

    # Livestatus related methods
    def as_live_dict(self, timeout=30):
        """
        Return a dict as expected for :meth:`live.MultiSiteConnection` method.
        """
        return {self.name: {
            'alias': self.alias,
            'socket': 'tcp:{0}:{1}'.format(self.ip_address, self.live_port),
            'nagios_url': self.nagios_url,
            'timeout': timeout,
            }}

    @staticmethod
    def live_connect(retries=3, *args, **kwargs):
        """
        Establish a connection to all satellites using livestatus.
        Returns the livestatus connection MultiSiteConnection object.

        :param timeout: the number of secs before connection is timed out.
        Default to 5 secs.
        :param retries: the number of retries if a satellite has failed.
        """
        satellites = Satellite.objects.filter(active=True)
        connection = None
        connection_settings = {}

        for sat in satellites:
            connection_settings.update(sat.as_live_dict(*args, **kwargs))

        for retry in xrange(0, retries):
            connection = Satellite.SatelliteConnection(connection_settings)
            if not connection.dead_sites():
                break

        if connection.dead_sites():
            exc = Satellite.SatelliteConnectError(connection.dead_sites())
            logger.exception(exc)
            raise exc

        return connection

    # String representation
    def __unicode__(self):
        return u'{0} ({1})'.format(self.name, self.alias)


class SecurityPort(models.Model):
    """
    Store port information needed on Firewalls in order to allow access from
    Nagios to monitored hosts.
    """
    NETWORK_PROTOCOL = (
        ('ICMP', 'ICMP'),
        ('TCP', 'TCP'),
        ('UDP', 'UDP'),
        ('TCP/UDP', 'TCP/UDP'),
    )

    name = models.CharField(max_length=64, help_text='Port name. eg. SNMP, SSH, etc...')
    description = models.CharField(max_length=128, help_text='Enter a description for this port.')
    begin_port = models.PositiveIntegerField(max_length=5, validators=[validate_network_port], help_text='Enter the begin port number.')
    end_port = models.PositiveIntegerField(max_length=5, validators=[validate_network_port], help_text='Enter the end port number. Keep it empty if none.', null=True, blank=True)
    protocol = models.CharField(max_length=7, choices=NETWORK_PROTOCOL, help_text='Choose the network protocol to use.')

    class Meta:
        ordering = ['name']

    def __unicode__(self):
        return self.name

apps/nagios/templates/nagios/ack_email_expired.html
{%  extends "common/base.html" %}

{%  block content %}
<div class="container">
    <div class="page-header">
        <h2>Central Monitoring Alert <small>Acknowledge an alert</small></h2>
    </div>

    <div class="alert alert-block alert-error">
        <h4 class="alert-heading">Token has expired !</h4>
        <p>This problem has been escalated. Nothing to do.<br><br></p>
        <a href="#modal-details" data-toggle="modal" class="btn">View details</a>    
    </div>

    <div class="modal fade hide" id="modal-details">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">×</button>
            <h3>Details about this alert</h3>
        </div>
        <div class="modal-body">
            <dl class="dl-horizontal">
                <dt>Author</dt><dd>{{ author }}</dd>
                <dt>Hostname</dt><dd>{{ hostname }}</dd>
                {% if service_description %}
                <dt>Service</dt><dd>{{ service_description }}</dd>
                {% endif %}
            </dl>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn" data-dismiss="modal">Close</button>
        </div>
    </div>

</div>
{%  endblock %}

apps/nagios/templates/nagios/ack_email_passed.html
{%  extends "common/base.html" %}

{%  block content %}
<div class="container">
    <div class="page-header">
        <h2>Central Monitoring Alert <small>Acknowledge an alert</small></h2>
    </div>

    <div class="alert alert-block alert-success">
        <h4 class="alert-heading">Successfully acknowledged !</h4>
        <p><br></p>
        <a href="#modal-details" data-toggle="modal" class="btn">View details</a>    
    </div>

    <div class="modal fade hide" id="modal-details">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">×</button>
            <h3>Details about this alert</h3>
        </div>
        <div class="modal-body">
            <dl class="dl-horizontal">
                <dt>Author</dt><dd>{{ author }}</dd>
                <dt>Hostname</dt><dd>{{ hostname }}</dd>
                {% if service_description %}
                <dt>Service</dt><dd>{{ service_description }}</dd>
                {% endif %}
            </dl>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn" data-dismiss="modal">Close</button>
        </div>
    </div>

</div>
{%  endblock %}

apps/nagios/templates/nagios/satellite_list.html
{% extends "common/base.html" %}

{% block page_title %}List of Monitoring systems{% endblock page_title %}

{% block page_content %}
<div class="container">
	<div class="page-header" xmlns="http://www.w3.org/1999/html">
	    <h1>Monitoring Systems <small>enabled in production</small></h1>
	</div>

	<p>This is the list of monitoring systems (aka Nagios Satellites) that are performing checks on monitored equipments.
		You will find the full list of systems enabled in production and the network ports that should be configured on firewalls.</p>

	<p>There is also a <em>web api</em> that permits to retrieve the details about satellites to be used in your scripts.</p>

	<div class="row">
		<div class="col-md-12">
			<div class="page-header">
				<h3>Nagios Satellites <small>enabled in production</small></h3>
			</div>

			{% if systems_list %}
				<table class="table table-hover table-condensed">
				    <thead>
				        <tr>
				            <th>Satellite</th>
				            <th>Gearman</th>
				            <th>Alias</th>
				            <th>Hostname</th>
				            <th>IP Address</th>
                            <th></th>
				        </tr>
				    </thead>
				    <tbody>
				        {% for sat in systems_list %}
                        <tr class="{% if sat.active %}success{% else %}warning{% endif %}">
                            <td><strong>{{ sat.name }}</strong></td>
                            <td>{% if sat.is_gearman %}<span class="glyphicon glyphicon-ok"></span>{% else %}<span class="glyphicon glyphicon-ban-circle"></span>{% endif %}</td>
				            <td>{{ sat.alias }}</td>
				            <td>{{ sat.fqdn }}</td>
				            <td>{{ sat.ip_address }}</td>
					        {% if perms.nagios.change_satellite %}<td><a target="_blank" title="Edit" href="{% url "admin:nagios_satellite_change" sat.id %}"><span class="glyphicon glyphicon-pencil"></span></a></td>{% endif %}
				        </tr>
				        {% endfor %}
				    </tbody>
				</table>
			{% else %}
				<p>No satellite configured.</p>
			{% endif %}

			<p class="pull-right">{% if perms.nagios.add_satellite %}<small><a target="_blank" href="{% url "admin:nagios_satellite_add" %}"><span class="glyphicon glyphicon-plus"></span> Add a new satellite</a></small>{% endif %}</p>
		</div>
	</div>

	<div class="row">
		<div class="col-md-12">
			<div class="page-header">
				<h3>Network ports <small>allow access from satellites to monitored equipments</small></h3>
			</div>

			{% if ports %}
				<table class="table table-hover table-condensed">
					<thead>
					<tr>
						<th>Name</th>
						<th>Description</th>
						<th>Protocol</th>
						<th>Port</th>
                        <th></th>
					</tr>
					</thead>
					<tbody>
					{% for port in ports %}
						<tr>
							<td>{{ port.name }}</td>
							<td>{{ port.description }}</td>
							<td>{{ port.protocol }}</td>
							<td>{% if port.end_port %}{{ port.begin_port }} - {{ port.end_port }}{% else %}{{ port.begin_port }}{% endif %}</td>
							{% if perms.nagios.change_securityport %}<td><a target="_blank" title="Edit" href="{% url "admin:nagios_securityport_change" port.id %}"><span class="glyphicon glyphicon-pencil"></span></a></td>{% endif %}
						</tr>
					{% endfor %}
					</tbody>
				</table>
			{% else %}
				<p>No port configured.</p>
			{%  endif %}

			<p class="pull-right">{% if perms.nagios.add_securityport %}<small><a target="_blank" href="{% url "admin:nagios_securityport_add" %}"><span class="glyphicon glyphicon-plus"></span> Register new port</a></small>{% endif %}</p>
			<div class="clearfix"></div>

			<p>You should pay attention to open the following ports on firewall in order to authorize satellites to query
				monitored equipments.</p>
			<p>Extra ports could be required for database connections, etc... this is on demand.</p>
		</div>
	</div>

    <div class="row">
		<div class="col-md-6 col-md-offset-3">
			<div class="page-header">
				<h3>Web API <small>use this in scripts</small></h3>
			</div>

			<p>Use the following Export URLs to have the list of satellites as JSON or CSV:</p>

			<ul>
				<li><strong>JSON</strong>: <code>{{ base_url }}{% url "satellites_export" format='json' %}</code></li>
				<li><strong>CSV</strong>: <code>{{ base_url }}{% url "satellites_export" format='csv' %}</code></li>
			</ul>
		</div>
    </div>
</div>
{% endblock %}