apps/kb/urls.py
from django.conf.urls import *

urlpatterns = patterns('apps.kb.views',
    url(r'^show/(?P<kb_namespace>.*)$', 'show_kb', name='show_kb'),
)

optools/urls.py
# -*- coding: utf-8 -*-
# Copyright (C) Canux CHENG <canuxcheng@gmail.com>
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
# DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
# OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

from django.conf.urls import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin

admin.autodiscover()

handler500 = 'monitoring.webui.views.server_error'

urlpatterns = patterns('',
    # Admin
    (r'^admin/', include(admin.site.urls)),

    # Applications
    # ============
    #
    # Portal
    (r'', include('apps.portal.urls')),
    (r'', include('monitoring.webui.urls')),
    (r'', include('apps.kpi.urls')),
    (r'^nagios/', include('apps.nagios.urls')),
    (r'^kb/', include('apps.kb.urls')),
)

apps/kb/models.py
"""
:mod:`apps.kb.models` -- Models for app kb.
"""

# Std imports
import os
import logging
import re
from datetime import datetime
from pprint import pformat

# Django imports
from django.utils.encoding import smart_str
from django.db import models
from django.core.exceptions import ValidationError
from django.utils.timezone import utc
from django.conf import settings


logger = logging.getLogger(__name__)

#===============================================================================
#   ____ _
#  / ___| | __ _ ___ ___  ___  ___
# | |   | |/ _` / __/ __|/ _ \/ __|
# | |___| | (_| \__ \__ \  __/\__ \
#  \____|_|\__,_|___/___/\___||___/
#
#===============================================================================

class Procedure(models.Model):
    """
    Procedure Model.
    Store informations about KB from Dokuwiki to a database.
    """
    namespace_regexp = r'^([a-zA-Z0-9_\-\.\+]+:*)+$'

    class MetaError(Exception):
        """Raised if error is encountered during meta file parsing."""
        pass

    # Possible rating choices
    RATING_CHOICES = (
        (-2, 'Bad'),
        (-1, 'Average'),
        ( 0, 'Good'),
        ( 1, 'Excellent'),
    )

    # Table columns
    namespace = models.CharField(max_length=255, unique=True, help_text='Namespace for this procedure.', editable=False)
    is_written = models.BooleanField(help_text='Is the procedure has been written ?', default=False, editable=False)
    validated = models.BooleanField(help_text='Is the procedure is validated ?', default=False, editable=False)
    author = models.CharField(max_length=128, help_text='Last modification author.', blank=True, null=True, editable=False)
    parents = models.ManyToManyField('Procedure', help_text='These are the parent procedures.', null=True, editable=False)
    rating = models.IntegerField(choices=RATING_CHOICES, help_text='Rating for this procedure.', default=-1)
    comment = models.TextField(help_text='Comment on the grade you given.', blank=True, null=True)
    last_modified = models.DateTimeField(help_text='Time of the last modification.', blank=True, null=True, editable=False)

    # KB constructor: register a new KB in the database with all details (without performing DB stuff)
    @classmethod
    def register(cls, namespace):
        procedure = cls(namespace=namespace)

        procedure._strip_namespace()
        procedure.update_meta()

        return procedure

    # Saving
    def save(self, *args, **kwargs):
        """Customize saving model method."""
        try:
            # Call validation manually
            self.full_clean()
        except ValidationError as e:
            logger.critical('Errors found about Procedure model validation ! Please fix them.')
            for error in e.message_dict['__all__']:
                logger.critical('%s', error)
            raise # Forward exception

        self.update_meta()

        # Check validation of the procedure
        try:
            before = Procedure.objects.get(pk=self.id)

            # Rating has changed...
            if self.rating != before.rating:
                logger.debug('Kb \"%s\" rating has changed. Validate.', self)
                self.validated = True

            # Last modified has changed...
            if self.last_modified != before.last_modified:
                logger.debug('Kb \"%s\" has been modified. Un-validate.', self)
                self.validated = False
        except Procedure.DoesNotExist:
            pass

        # Save in DB
        super(Procedure, self).save(*args, **kwargs)

    # Special KB methods
    def update_meta(self):
        """Update META information about the procedure."""
        # Check if file exist for the procedure
        if os.path.isfile(self.get_filename()):
            self.is_written = True
        else:
            self.is_written = False

        # Update META informations
        self._populate_meta()

    def get_name(self):
        """Get the name for this procedure."""
        return self.namespace.split(':')[-1]

    def get_filename(self):
        """Get the filename for this procedure."""
        return os.path.join(settings.DOKUWIKI_PAGES_DIR, "{}.txt".format(self.namespace.replace(':', '/')))

    def get_changes_filename(self):
        """Get the filename containing changes for this procedure."""
        return os.path.join(settings.DOKUWIKI_META_DIR, "{}.changes".format(self.namespace.replace(':', '/')))

    def get_read_url(self):
        """Get the URL to read the procedure online."""
        return '{}/{}'.format(settings.DOKUWIKI_BASE_URL, self.namespace)

    def get_edit_url(self):
        """Get the URL to edit the procedure online."""
        return '{}/{}?do=edit'.format(settings.DOKUWIKI_BASE_URL, self.namespace)

    def _populate_meta(self):
        """Populate META information about the Kb."""
        try:
            with open(self.get_changes_filename(), 'r') as meta_file:
                last_change = meta_file.readlines()[-1].split('\t')
                logger.debug("Parsing line:\n%s", pformat(last_change))
                self.last_modified = datetime.fromtimestamp(long(last_change[0]), tz=utc)
                self.author = last_change[4]
        except IOError:
            # Do nothing. No meta information available, procedure may not exist
            logger.debug('No META information for \"%s\".', self)
            pass
        except ValueError:
            # Can occur if timestamp cannot be converted to datetime or if it is not found
            raise Procedure.MetaError('Error during meta file \"%s\" parsing !' % self.get_changes_filename())

    def _strip_namespace(self):
        """
        Clean and validate namespace.
        """
        logger.debug('Cleaning namespace \'%s\'...', self.namespace)
        self.namespace = self.namespace.lower().strip(':')

        if not re.match(Procedure.namespace_regexp, self.namespace):
            raise ValidationError('KB namespace should be of the form %s !' % Procedure.namespace_regexp)

        logger.debug('Namespace cleaned to \'%s\'.', self.namespace)

    def get_parents(self):
        """
        Build the list of parent namespaces for the procedure.

        :return: parent list for procedure ``['app:toto', 'app:toto:tata', '...']``.
        """
        parents_to_build = []
        parents = filter(str, self.namespace.split(':')[:-1])

        for index, parent in enumerate(parents):
            index += 1
            parents_to_build.append(":".join(parents[:index]))

        return parents_to_build

    def _linkify_parents(self):
        """Make parents relations."""
        for parent_name in self.get_parents():
            try:
                parent_model = Procedure.objects.get(namespace=parent_name)
            except Procedure.DoesNotExist:
                parent_model = Procedure.register(namespace=parent_name)

            self.parents.add(parent_model)

    # Comparaison operators
    def __eq__(self, other):
        if isinstance(other, (str, unicode)):
            return other == self.namespace
        elif isinstance(other, Procedure):
            return self.namespace == other.namespace

        super(Procedure, self).__eq__(other)

    # Misc
    def __str__(self):
        return smart_str(self.namespace)

    def __unicode__(self):
        return self.namespace

    def __hash__(self):
        return hash(self.namespace)

apps/kb/forms.py
"""Forms for the app kb."""

# Django imports
from django import forms

# Models imports
from apps.kb.models import Procedure


SEP_RATING_CHOICES = (
    ('', 'Please select rating'),
    ('', '--------------------'),
)

RATING_CHOICES = SEP_RATING_CHOICES + Procedure.RATING_CHOICES

# Comment form
class ProcedureCommentForm(forms.Form):
    rating = forms.ChoiceField(choices=RATING_CHOICES, label='Select rating to apply')
    comment = forms.CharField(widget=forms.Textarea(), label='Enter a comment about your choice')

apps/kb/views.py
"""
Django views for application kb.
"""

# Std imports
import logging
from pprint import pformat

# Django imports
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

# Models imports
from apps.kb.models import Procedure


logger = logging.getLogger(__name__)

@login_required
def show_kb(request, kb_namespace):
    """
    Handle the way KB is shown.

    Try to find the first procedure found in ``kb_namespace``. Redirect to first found if
    the requested procedure is not found and user is not a KB Manager.

    For peoples member of group **kb_manager**, propose to create the procedure
    if missing (all namespaces).

    For others, it says that the procedure is missing and the alert should be
    part of a Stratos ticket to the relevant group.

    :param kb_namespace: the dokuwiki procedure page of the form ``xxx:xxx:xxx...``.

    Template:
        kb/manage_procedure.html

    Context:
        title
        show_main_menu
        kb_found
        kb_requested
        user_is_helpdesk
        procedure_pages
    """
    try:
        logger.info('User \'%s\' (%s) is requesting the KB: \'%s\'',
            request.user.username, ",".join(request.user.groups.values_list('name', flat=True)), kb_namespace)
    except:
        logger.info('Guest user is requesting the KB: \'%s\'', kb_namespace)

    user_is_helpdesk = request.user.groups.filter(name='helpdesk').exists()
    procedure_pages = []
    kb_found = None

    # Init the KB object...
    try:
        kb_requested = Procedure.objects.get(namespace=kb_namespace)
    except Procedure.DoesNotExist:
        kb_requested = Procedure.register(namespace=kb_namespace)

    # .. and its parents
    for parent in kb_requested.get_parents():
        try:
            parent_model = Procedure.objects.get(namespace=parent)
        except Procedure.DoesNotExist:
            parent_model = Procedure.register(namespace=parent)

        procedure_pages.append(parent_model)
    procedure_pages.append(kb_requested)

    # Try to find if there is any procedure existing in the namespace
    for page in procedure_pages:
        if page.is_written:
            kb_found = page

    # Populate the context
    context = {
        'title': "Showing KB %s" % kb_requested.namespace,
        'show_main_menu': False,
        'kb_found': kb_found,
        'kb_requested': kb_requested,
        'user_is_helpdesk': user_is_helpdesk,
        'procedure_pages': procedure_pages,
    }

    logger.debug('Debugging context for rendering template for KB...\n%s', pformat(context))

    # Redirect to the procedure if the requested is created
    if kb_requested and kb_requested.is_written:
        return redirect(kb_requested.get_read_url())
    # Redirect to the first procedure found if user is not helpdesk
    if kb_found and (user_is_helpdesk or request.user.is_anonymous()):
        return redirect(kb_found.get_read_url())
    # No procedure exist or user is not helpdesk
    else:
        return render(request, "kb/manage_procedure.html", context)

apps/kb/templates/kb/manage_procedure.html
{% extends "common/base.html" %}

{% block extra_css %}
  <link href="{{ STATIC_URL }}kb/css/kb.css" rel="stylesheet">
{% endblock extra_css %}

{% block page_title %}Manage KB namespace{% endblock page_title %}

{% block page_content %}
  {% if user.is_authenticated and not user_is_helpdesk %}
    <div class="jumbotron">
      <div class="container">
        <h1>Discover KB Management system</h1>

        <p>This new system handles the procedure creation and organization.
          It was done to introduce a way to create more general procedure,
          with the possibility to create specific ones like before.</p>

        <a href="http://canuxcheng.com/doc/kb/index.html"
             class="btn btn-primary btn-lg" target="_blank"><i
                  class="glyphicon glyphicon-question-sign"></i> Learn how to use it</a>
      </div>
    </div>
  {% endif %}

  <div class="container">
    <div class="page-header">
      <h1>Procedure management
        <small>for <strong>{{ kb_requested.namespace }}</strong></small>
      </h1>
    </div>

    <div class="row">
      <div class="col-md-12">
        {% if not kb_found %}
          <h4 class="alert alert-danger">The requested <a
                  href="javascript:void(0);" rel="tooltip"
                  title="Procedure">KB</a>
            does not contains any valid procedure within all namespaces !</h4>
        {% else %}
          <h4 class="alert alert-warning">The requested <a
                  href="javascript:void(0);" rel="tooltip"
                  title="Procedure">KB</a>
            does not exist but there are some at others levels !</h4>
        {% endif %}

        {% if user.is_authenticated and not user_is_helpdesk %}
          <p>It appears that you are responsible to create procedures for
            alerts. You are invited to create the
            procedure now, please select the namespace where you want to edit
            the procedure.</p>

          <p>More you go to the right, more precise will be your procedure. More
            you go to the left, more general will be your procedure.</p>

          <ul class="kb-namespace-select">
            {% for kb in procedure_pages %}
              {% if forloop.first %}{{ kb.get_name }}{% else %}
                <span class="dropdown">
                <a class='{% if not kb.is_written %}kb-link-missing {% endif %}dropdown-toggle'
                   id="drop_{{ kb.namespace }}" role="button"
                   data-toggle="dropdown" href="#">{{ kb.get_name }}</a><ul
                        class="dropdown-menu" role="menu"
                        aria-labelledby="drop_{{ kb.namespace }}">
                  <li><a tabindex="-1" href="{{ kb.get_edit_url }}">Edit</a>
                  </li>
                  {% if kb.is_written %}
                    <li><a tabindex="-1" href="{{ kb.get_read_url }}">Read</a>
                    </li>{% endif %}</ul></span>{% endif %}
              {% if not forloop.last %}
                <span class="divider">:</span>
              {% endif %}
            {% endfor %}
          </ul>

          <h4>Legend</h4>
          <ul>
            <li><strong>namespace</strong> - Cannot be created, used as a
              folder.
            </li>
            <li><strong class="kb-link-missing">namespace</strong> - Missing,
              should be created.
            </li>
            <li><strong><a>namespace</a></strong> - Link to procedure exist.
            </li>
          </ul>
        {% else %}
          <p>Please get in contact with the application or system responsibles
            in order to make them create the
            procedure to handle this alert.</p>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock page_content %}

apps/kb/templates/kb/rate.html
{% extends "common/base.html" %}

{% block content %}
<div class="container">
    <div class="page-header">
    <h1>Rate selected procedures</h1>
    </div>

    <p>You are about to rate the following procedures:</p>

    <div class="row">
        <div class="span6">
            <ul>{{ procedures|unordered_list }}</ul>
        </div>

        <div class="span6">
            {% if comment_form.errors %}
                <div class="alert alert-error">
                    <p>Please correct the following errors.</p>
                    {{ comment_form.errors }}
                </div>
            {% endif %}

            <form action="" method="post">{% csrf_token %}
                {{ comment_form.rating.label_tag }}
                {{ comment_form.rating }}

                {{ comment_form.comment.label_tag }}
                <textarea id="id_comment" name="comment" class="input-xxlarge" placeholder="Enter your comment here..." rows="5"></textarea>

                {% for id in ids %}
                <input type="hidden" name="_selected_action" value="{{ id }}">
                {% endfor %}
                <input type="hidden" name="action" value="rate_and_comment" />
                <input type="hidden" name="posted" value="yes" />
                <p><button type="submit" class="btn btn-primary">Apply</button></p>
            </form>
        </div>
    </div>
</div>
{% endblock %}